language: node_js
node_js:
  - node  # latest stable
  - lts/* # latest LTS
services:
  - redis-server
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm install redis --production
  - npm test
